<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>3.3.0</Version>
    <AssemblyVersion>3.3.0.0</AssemblyVersion>
    <FileVersion>3.3.0.0</FileVersion>
    <Product>Motion Commander</Product>
    <Company>BlackTecCom - Jaborov Daler</Company>
    <Authors>BlackTecCom - Jaborov Daler</Authors>
    <Copyright>Copyright © 2026 BlackTecCom - Jaborov Daler. All rights reserved.</Copyright>
    <Description>All-in-One High-Performance File Manager, Archive Tool, and Storage Control Center</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/BlackTecCom2000/MotionCommander</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SharpCompress" Version="0.50.4" />
    <PackageReference Include="System.Management" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\MotionCommander.Core\MotionCommander.Core.csproj" />
  </ItemGroup>

</Project>
